# -*- coding: utf-8 -*-
"""truonghiendat_assignment2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLK5kfuX9zie73ROrANrbHQg4lbSyccT
"""

from google.colab import files
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np
from google.colab.patches import cv2_imshow

uploaded = files.upload()

img = cv.imread('Assignment2.png')
cv2_imshow(img)

"""## **# histogram_equalization**"""

# to run in google colab
import sys

if "google.colab" in sys.modules:
    import subprocess

    subprocess.call("apt-get install subversion".split())
    subprocess.call(
        "svn export https://github.com/YoniChechik/AI_is_Math/trunk/c_02a_basic_image_processing/Unequalized_Hawkes_Bay_NZ.jpg".split()
    )

figsize = (10, 10)

"""First, read the image as grayscale"""

# read as grayscale
I = cv.imread("Assignment2.png", 0)

plt.figure(figsize=figsize)
plt.imshow(I, cmap="gray", vmin=0, vmax=255)
plt.title("Original image")
plt.show()

"""Let's start by calculating and showing the original histogram"""

bins_edges_min_max = [0, 256]
num_bins = 256
bin_count, bins_edges = np.histogram(I, num_bins, bins_edges_min_max)
bins_start = bins_edges[:-1]

def draw_hist(x_axis, input):
    fig, ax = plt.subplots(figsize=figsize)
    # why not using plt.hist? because we want to plot also some derivations of this hist, so this is easier
    plt.bar(x_axis, input, width=input.shape[0] / (x_axis[-1] - x_axis[0] + 1))
    return fig, ax


draw_hist(bins_start, bin_count)
plt.title("Original histogram")
plt.show()

"""Normalize the histogram to gat a discrete PDF"""

pdf = bin_count / np.sum(bin_count)

draw_hist(bins_start, pdf)
plt.title("Original PDF")
plt.show()

"""Get the CDF by calculating the cumulative sum of the pdf data"""

cdf = np.cumsum(pdf)

plt.figure(figsize=figsize)
plt.plot(cdf)
plt.title("Original CDF")
plt.show()

fig, ax = draw_hist(bins_start, pdf)
ax.plot(cdf * np.max(pdf), "r")
plt.title("Original PDF+ const*CDF to show the connection between the two")
plt.show()

"""The final step is to un-normalize the CDF to become the equalization function"""

f_eq = np.round(cdf * 255).astype(int)

f_eq

"""Use the equalization function to get the equalized image"""

I_eq = f_eq[I]

plt.figure(figsize=figsize)
plt.imshow(I_eq, cmap="gray", vmin=0, vmax=255)
plt.title("equalized image")
plt.show()

"""Plot the equalized histogram, PDF and CDF"""

bin_count, bins_edges = np.histogram(I_eq, num_bins, bins_edges_min_max)
bins_start = bins_edges[:-1]

draw_hist(bins_start, bin_count)
plt.title("equalized histogram")
plt.show()

pdf = bin_count / np.sum(bin_count)
cdf = np.cumsum(pdf)

fig, ax = draw_hist(bins_start, pdf)
ax.plot(cdf * np.max(pdf), "r")
plt.title("equalized PDF and const*CDF")
plt.show()

"""cv2 histogram equalization function"""

Img_eq_cv2 = cv.equalizeHist(I)

plt.figure(figsize=figsize)
plt.imshow(Img_eq_cv2, cmap="gray", vmin=0, vmax=255)
plt.title("cv2.equalizeHist() result")
plt.show()

ADAPTIVE HISTOGARM EQUALIZATION- CLAHE

import cv2
import numpy as np

# Reading the image from the present directory
image = cv.imread("Assignment2.png")
# Resizing the image for compatibility
image = cv.resize(image, (500, 600))

# The initial processing of the image
image = cv2.medianBlur(image, 3)
image_bw = cv.cvtColor(image, cv.COLOR_BGR2GRAY)

# The declaration of CLAHE
# clipLimit -> Threshold for contrast limiting
clahe = cv.createCLAHE(clipLimit=5)
final_img = clahe.apply(image_bw) + 30

# Ordinary thresholding the same image
_, ordinary_img = cv.threshold(image_bw, 155, 255, cv2.THRESH_BINARY)

# Showing the two images
cv2_imshow(ordinary_img)
cv2_imshow(final_img)

"""**HISTOGRAM MATCHING**"""

uploaded = files.upload()

from skimage.exposure import match_histograms
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

img = cv.imread("assignment2_mimic.png")
source = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

img_t = cv.imread("Assignment2.png")
target = cv.cvtColor(img_t, cv.COLOR_BGR2GRAY)

cv2_imshow(source)
cv2_imshow(target)

matched = match_histograms(source, target, channel_axis=None)
cv2_imshow(matched)
cv2_imshow(target)